### PR TITLE
Add support for Lumin / Magic Leap

### PR DESCRIPTION
**Pull request by Nihav-Jain**
Uses android arm64 library

### CODE REVIEW

**Comment by Nihav-Jain** [comment]
fixes issue #41

**Comment by atteneder** [comment]
Hi @Nihav-Jain,

Thanks for this great text book PR! I have no hardware to test/confirm, but this looks straightforward to me, so I'll merge.

You rock!

**Comment by Nihav-Jain** [comment]
Thanks @atteneder. I'm happy to test and maintain Lumin support for future updates of this plugin.

**Comment by atteneder** [comment]
@Nihav-Jain That would be great! Thanks for the offer ❤️

**Pull request merged**
